### PR TITLE
fix: incorrect update progress bar visibility check

### LINKED ISSUE #710: bug: update app should show `in progress` again
**Describe the bug**
We got rid of the app update downloading status bar, so we do see how logn it takes apps to update. The app just appears frozen

**To Reproduce**
1. Open old version
2. Click download new version
3. App "freezes" for up to 1 minute 
4. Get restart prompt

**Expected behavior**
See download progress, so I dont think something went wrong and quit the app

**Desktop (please complete the following information):**
 - OS: mac m1
 - Version: 0.3.2, 0.3.1

**Additional context**

### PR DESCRIPTION
**Pull request by louis-jan**
## Problem
The app fails to display the update progress again due to an incorrect conditional check for visibility

Fixed #710 

Screenshot 2023-11-24 at 11 52 41
Screenshot 2023-11-24 at 11 52 47

### CODE REVIEW

File: web/containers/Layout/BottomBar/index.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ const BottomBar = () => {
     <div className="fixed bottom-0 left-16 z-20 flex h-12 w-[calc(100%-64px)] items-center justify-between border-t border-border bg-background/50 px-3">
       <div className="flex flex-shrink-0 items-center gap-x-2">
         <div className="flex items-center space-x-2">
-          {!progress && progress === 0 ? (
```
Comment (louis-jan) [inline web/containers/Layout/BottomBar/index.tsx:34]: I think this is from conflict resolving, right? @urmauur.

**Review by namchuai — APPROVED** [review]
