### PR TITLE
fix: update the condition for generating the title

### LINKED ISSUE #3121: bug: avoid 2nd remote API request to generate thread titles
## Goal 

- When using remote API, we should not send 2nd inference request to generate thread title (costs $$, especially for long requests)
    - Just use 1st request text as thread title 
- This is different from Local AIs, where the 2nd thread generation request is local and cost-less

## Alternatives considered

- Settings page: rejected b/c introduces complexity

## Original Issue
```
### #

- [X] I have searched the existing issues

### Current behavior

If you do not set a title to a new chat thread before sending a message to the Claude Sonnet 3.5 API, you will be sending duplicate inputs. Please consider adding a check or force user to input a new title before sending a message.

### Minimum reproduction step

Add Claude Sonnet 3.5 Model
Create new chat
Don’t edit the chat title
API shows duplicate inputs

### Expected behavior

Send a single input even if you forget to change the title.

### Screenshots / Logs

Jun 27, 2024, 10:58 AM    claude-3-5-sonnet-20240620    1.41    1046    22    http    None
Jun 27, 2024, 10:58 AM    claude-3-5-sonnet-20240620    3.89    1028    159    http    None
Jun 27, 2024, 10:50 AM    claude-3-5-sonnet-20240620    16.14    22595    1117    http    None
Jun 27, 2024, 10:50 AM    claude-3-5-sonnet-20240620    12.92    25658    853    http    None
Jun 27, 2024, 10:46 AM    claude-3-5-sonnet-20240620    11.73    22595    704    http    None
Jun 27, 2024, 10:46 AM    claude-3-5-sonnet-20240620    12.84    22577    699    http    None
Jun 27, 2024, 10:44 AM    claude-3-5-sonnet-20240620    0.92    401    19    http    None
Jun 27, 2024, 10:44 AM    claude-3-5-sonnet-20240620    6.77    383    401    http    None


### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

_No response_
```

### PR DESCRIPTION
**Pull request by urmauur**
## Describe Your Changes
Preventing title generation. This ensures that the title generation logic runs only for local models

### Changes code
Added new condition on `generateThreadTitle`

https://github.com/user-attachments/assets/707b0026-ca60-475d-8499-9f03654ddad2

## Fixes Issues

- Closes #3121 
- Closes #

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by louis-jan — APPROVED** [review]

File: web/containers/Providers/EventHandler.tsx [hunk 1]
```diff
@@ -234,7 +236,11 @@ export default function EventHandler({ children }: { children: ReactNode }) {
       return
     }
 
-    if (!activeModelRef.current) {
+    // Check model engine; we don't want to generate a title when it's not a local engine.
+    if (
+      !activeModelRef.current ||
+      !localEngines.includes(activeModelRef.current?.engine as InferenceEngine)
+    ) {
```
Comment (louis-jan) [inline web/containers/Providers/EventHandler.tsx:243]: Missing test cases for the logic

Comment (louis-jan) [reply web/containers/Providers/EventHandler.tsx:243]: I will add later
