### PR TITLE
Fix: Improve Llama.cpp model path handling and error handling

### LINKED ISSUE #6037: bug: v0.6.6 Unable to load any models
**Version:** v0.6.6

## Describe the Bug

I used to be able to run a local server on Jan in 6.5 but ever since I updated to 6.6 It's been unable to load any models, even the ones I downloaded directly from the hub. Apologies if I'm getting any part of this format wrong, this is my first time on Github and my first time writing a report.

## Steps to Reproduce
1. Start Jan
2. Attempt to load a model from llama.cpp
3. Press start
4. Error window pops up

## Screenshots / Logs

Image

Image

[app.log](https://github.com/user-attachments/files/21567134/app.log)

## Operating System
- [ ] MacOS
- [X] Windows
- [ ] Linux

### PR DESCRIPTION
**Pull request by qnixsynapse**
## Describe Your Changes
This change refactors the load_llama_model function to improve how it handles and validates the model path.

Previously, the function extracted the model path but did not perform any validation. This change adds the following improvements:

It now checks for the presence of the -m flag.

It verifies that a path is provided after the -m flag.

It validates that the specified model path actually exists on the filesystem.

It ensures that the SessionInfo struct stores the canonical display path of the model, which is a more robust approach.

These changes make the model loading process more reliable and provide better error handling for invalid or missing model paths.

## Fixes Issues [TBD]

- Closes #6037 (probably)
- Closes #

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

----

> [!IMPORTANT]
> Improves `load_llama_model` path handling and error handling, especially for Windows, by validating model paths and using short paths.
> 
>   - **Behavior**:
>     - `load_llama_model` in `server.rs` now checks for `-m` flag presence and validates the model path.
>     - On Windows, uses `get_short_path` to convert model paths to short paths.
>     - Removes error channel logic, simplifying error handling.
>   - **Error Handling**:
>     - Adds detailed error messages for missing `-m` flag and invalid model paths.
>     - Refines process exit error handling by removing redundant error checks.
>   - **Windows Specific**:
>     - Adds `get_short_path` function to handle Windows path conversion.
>     - Updates `Cargo.toml` to include `windows-sys` and `tempfile` dependencies for Windows.
>   - **Tests**:
>     - Adds `test_path_with_uncommon_dir_names` to verify path handling with non-ASCII characters.
>     - Updates existing tests to align with new error handling logic.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=menloresearch%2Fjan&utm_source=github&utm_medium=referral)<sup> for 9444d7030b3054446beae2070506dcd30e9c9e4d. You can [customize](https://app.ellipsis.dev/menloresearch/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src-tauri/src/core/utils/extensions/inference_llamacpp_extension/server.rs [hunk 1]
```diff
@@ -332,7 +381,7 @@ pub async fn load_llama_model(
         pid: pid.clone(),
         port: port,
         model_id: model_id,
-        model_path: model_path,
+        model_path: model_path_pb.display().to_string(),
```
Comment (louis-jan) [inline src-tauri/src/core/utils/extensions/inference_llamacpp_extension/server.rs:355]: Add tests for the new changes
