### PR TITLE
fix: #3558 wrong model metadata import or download from HuggingFace

### LINKED ISSUE #3558: bug: Dropping GGUF metadata when creating `model.yaml` for Model Downloaded via URL
**Describe the bug**
When downloading the HF GGUF model via URL import from the model hub, the model is using default settings instead of the correct settings. The fixed context length is set to 2048, the prompt template is incorrect, and there is an issue with the stop word. However, importing GGUF directly seems to resolve these issues.

**Steps to reproduce**
1. Download the HF GGUF model from the model hub using URL import.
2. Check the settings for context length, prompt template, and stop word.
3. Compare the settings with the correct settings for the GGUF model.

**Expected behavior**
The HF GGUF model downloaded via URL import should have the correct settings for context length, prompt template, and stop word, matching the settings when GGUF is imported directly.

**Additional context**
The issue seems to be specific to downloading the HF GGUF model via URL import from the model hub. Importing GGUF directly does not exhibit the same issue with default settings.

Comparing model.json, the GGUF direct import in on the right 
image

### LINKED ISSUE #3708: bug: Model downloaded from Hugging Face can only run on CPU because it doesn't retrieve the correct GGUF model's metadata
### Jan version

Jan v0.5.4

### Describe the Bug

The installed models via app hub, works on GPU as was, but in this version the user installed models use only CPU. In the older version the user installed models also used GPU.
Each new version ruins using of the user installed models 😭🤬

### Steps to Reproduce

1. Install manually models from hugging face and from Jan hub.
2. Run one, then the other.
3. In this version the user installed not uses GPU.

### Screenshots / Logs

_No response_

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### LINKED ISSUE #3714: bug: Wrong maximum context length for qwen2.5-coder
### Jan version

v0.5.4

### Describe the Bug

Using qwen-2.5-coder-7b-instruct, Jan allows a maximum context length of 2048 tokens. However, both according to qwen's website as well as llama.cpp's output (most recent version from github at the time of writing), the maximum context length is 131072 tokens.

```
build: 3787 (6026da52) with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for x86_64-linux-gnu
system info: n_threads = 47, n_threads_batch = 47, total_threads = 48

system_info: n_threads = 47 (n_threads_batch = 47) / 48 | AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | AVX512_BF16 = 1 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 

main: HTTP server is listening, hostname: 127.0.0.1, port: 8080, http threads: 47
main: loading model
llama_model_loader: additional 2 GGUFs metadata loaded.
llama_model_loader: loaded meta data with 29 key-value pairs and 339 tensors from [...]/qwen-2.5/qwen2.5-coder-7b-instruct-q8_0-00001-of-00003.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Qwen2.5 Coder 7B Instruct GGUF
llama_model_loader: - kv   3:                           general.finetune str              = Instruct-GGUF
llama_model_loader: - kv   4:                           general.basename str              = Qwen2.5-Coder
llama_model_loader: - kv   5:                         general.size_label str              = 7B
llama_model_loader: - kv   6:                          qwen2.block_count u32              = 28
llama_model_loader: - kv   7:                       qwen2.context_length u32              = 131072
llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 3584
llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 18944
llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 28
llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 4
llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  14:                          general.file_type u32              = 7
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - kv  26:                                   split.no u16              = 0
llama_model_loader: - kv  27:                                split.count u16              = 3
llama_model_loader: - kv  28:                        split.tensors.count i32              = 339
```

Unfortunately this makes the model within Jan not really usable for coding related tasks.

### Steps to Reproduce

1. Install current Jan release (0.5.4) as debian package
2. Download qwen-2.5-coder-7b-instruct  8b (https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/tree/main)
3. Import model into Jan
4. Select model in "Model" tab
5. Scroll down to "Context Length" in "Model tab"
6. 2048 is  the maximum allowed value

To my understanding, even without ROPE 2048 is way below the trained context length of qwen-2.5 coder.

### Screenshots / Logs

image

Unfortunately, there are no logs under `~/jan/logs` (I did a find over all of my home folder for an `app.log` file, but none were found).

Maybe I'll checkout the repo and debug this myself later on.

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### PR DESCRIPTION
**Pull request by louis-jan**
## Describe Your Changes

When downloading the HF GGUF model via URL import from the model hub, the model is using default settings instead of the correct settings. The fixed context length is set to 2048, the prompt template is incorrect, and there is an issue with the stop word. However, importing GGUF directly seems to resolve these issues.

### Steps to reproduce

Download the HF GGUF model from the model hub using URL import.
Check the settings for context length, prompt template, and stop word.
Compare the settings with the correct settings for the GGUF model.

### Expected behavior
The HF GGUF model downloaded via URL import should have the correct settings for context length, prompt template, and stop word, matching the settings when GGUF is imported directly.

### Additional context
The issue seems to be specific to downloading the HF GGUF model via URL import from the model hub. Importing GGUF directly does not exhibit the same issue with default settings.

## Fixes Issues

- Fixes #3558
- Fixes #3714 
- Fixes #3708

## Screenshots 
| Qwen 2.5 download from HF |
|:-:|
|Screenshot 2024-09-23 at 20 41 21|

## Code Changes

1. `extensions/model-extension/src/index.test.ts`
2. `extensions/model-extension/src/index.ts`
3. `extensions/model-extension/src/node/index.ts`
4. `extensions/model-extension/src/node/node.test.ts`

Here's a summary of the major changes across these files:

### `index.test.ts`
- Added mock functions for new dependencies (`downloadMock`, `mkdirMock`, `writeFileSyncMock`, `copyFileMock`).
- Added setup for a global `fetch` mock.
- Imported additional functions for testing (`renderJinjaTemplate`, `Template`).
- Added a new test case for `downloadModel` with invalid gguf metadata.

### `index.ts`
- Added support for downloading HF model metadata by fetching and retrieving GGUF metadata.
- Improved the creation and update of model settings and parameters using fetched metadata.
- Added a new method `retrieveGGUFMetadata` that returns a partially updated model based on metadata.
- Handled conflicts and updated `parameters` and `settings` using GGUF metadata.
- Refactored the eos token handling and merging model configurations.

### `node/index.ts`
- Removed the original implementation of `renderedTemplate` from the GGUF metadata parsing process.
- Added a new function `renderJinjaTemplate` for parsing Jinja templates based on the metadata.

### `node/node.test.ts`
- Added tests for the `renderJinjaTemplate` function.
- Includes tests handling cases where token IDs are missing or the template is empty.

### Detailed Examples
- **GGUF Metadata Handling**: Added code to check for and update model settings based on metadata attributes like `eos_token_id`, `context_length`, `block_count`, etc.
  ```typescript
  await fs.writeFileSync(modelJsonPath, JSON.stringify(model, null, 2))
  const updatedModel = await this.retrieveGGUFMetadata(metadata)
  model.settings = { ...model.settings, ...updatedModel.settings };
  ```

- **Infrastructural Mocks in Tests**: Created mocks and their respective test setups to emulate filesystem and network behaviors for more deterministic tests.
  ```typescript
  global.fetch = jest.fn(() => Promise.resolve(...));
  expect(sut.downloadModel(...)).rejects.toBeTruthy();
  ```

These changes all seem aimed to improve the robustness and flexibility of model handling within the codebase, especially concerning dynamically adjusting to metadata from fetched models.

### CODE REVIEW

**Comment by dan-homebrew** [comment]
Thank you @louis-jan!

File: extensions/model-extension/src/index.ts [hunk 1]
```diff
@@ -556,6 +573,7 @@ export default class JanModelExtension extends ModelExtension {
     )
 
     const eos_id = metadata?.['tokenizer.ggml.eos_token_id']
+    const updatedModel = await this.retrieveGGUFMetadata(metadata)
```
Comment (dan-homebrew) [inline extensions/model-extension/src/index.ts:576]: This is much needed - thank you @louis-jan!

**Review by dan-homebrew — APPROVED** [review]

**Review by urmauur — APPROVED** [review]

File: extensions/model-extension/src/index.ts (hunk 1 above)
Comment (louis-jan) [reply extensions/model-extension/src/index.ts:575]: Thanks for the comment. I noticed that eos_id appears to be legacy code, which we should consider cleaning up. Removed.
