### PR TITLE
bugs: fix stop streaming when user delete or clean thread

### LINKED ISSUE #1322: bug: deleting another thread while one thread is generating output causes an interruption
**Describe the bug**
[A clear and concise description of what the bug is.](https://discord.com/channels/1107178041848909847/1190819039635853393/1191681947911606402)
Screenshot 2024-01-04 at 11 40 18

**Steps to reproduce**
1. Send a message 
2. Click delete another thread while the message is still streaming
3. See error

**Expected behavior**
Should not interrupt the stream, message should be delivered

### PR DESCRIPTION
**Pull request by urmauur**
## Describe Your Changes
Fix stop streaming when user delete and clean thread

## Fixes Issues
fixes #1322 

https://github.com/janhq/jan/assets/10354610/1bb6daee-1022-4518-b1c2-ad25491f71a8

### CODE REVIEW

File: web/screens/Chat/ThreadList/index.tsx [hunk 1]
```diff
@@ -89,7 +90,10 @@ export default function ThreadList() {
               className={twMerge(
                 `group/message relative mb-1 flex cursor-pointer flex-col transition-all hover:rounded-lg hover:bg-gray-100 hover:dark:bg-secondary/50`
               )}
-              onClick={() => onThreadClick(thread)}
+              onClick={() => {
+                console.log('a')
```
Comment (louis-jan) [inline web/screens/Chat/ThreadList/index.tsx:94]:
```suggestion
```

**Review by louis-jan — APPROVED** [review]
LGTM
