### PR TITLE
Rearrange model position in Hub page

### LINKED ISSUE #2532: bug: Hub - The order of models should be: Featured -> Ascending order (Remote -> Local)
**Describe the bug**
The order of models displayed on the page is not in the right order:
1. Featured label
2. Ascending order (Remote -> Local).

**Steps to reproduce**
1. Go to Hub page.
3. Check the order of models displayed.

**Expected behavior**
The models should be displayed in the right order Featured label-> Ascending order (Remote -> Local)

**Screenshots**
image

**Environment details**
Happening on all OS

### PR DESCRIPTION
**Pull request by Inchoker**
## Describe Your Changes

-Rearrange using following condition:
1. Featured models -> remote models -> local models -> remaining models
2. Each of categories are sorted by name ascendingly

## Fixes Issues

- Closes #2532 

## Self Checklist

- [x] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

File: web/screens/ExploreModels/ExploreModelList/index.tsx [hunk 1]
```diff
@@ -1,50 +1,46 @@
+import { useMemo } from 'react'
+
 import { Model } from '@janhq/core'
 
+import { useAtomValue } from 'jotai'
+
 import ExploreModelItem from '@/screens/ExploreModels/ExploreModelItem'
 
+import { downloadedModelsAtom } from '../../../helpers/atoms/Model.atom'
```
Comment (louis-jan) [inline web/screens/ExploreModels/ExploreModelList/index.tsx:9]:
```suggestion
import { downloadedModelsAtom } from '@/helpers/atoms/Model.atom'
```

**Review by louis-jan — APPROVED** [review]
LGTM
