### PR TITLE
fix: #271 Cannot read properties of undefined (reading 'map')

### LINKED ISSUE #271: bug: v0.1.3 Cannot read properties of undefined (reading 'map')
**Describe the bug**

**To Reproduce**
1. Download a fresh 0.1.3
2. Open teh app
3. Get error

**Error Message**
```sh
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'map')
at /Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/dist/module.js:125:21
at replacement (/Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/node_modules/sqlite3/lib/trace.js:25:27)
at Statement.errBack (/Users/nicolezhu/Library/Application Support/jan-electron/plugins/data-plugin/node_modules/sqlite3/lib/sqlite3.js:15:21)
```

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: mac arm64

### PR DESCRIPTION
**Pull request by louis-jan**
- getFinishedDownloadModels is assumed that the selected rows would never return undefined

fixes #271

### CODE REVIEW

File: electron/core/plugins/data-plugin/module.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ function getFinishedDownloadModels() {
 
     const query = `SELECT * FROM models WHERE finish_download_at != -1 ORDER BY finish_download_at DESC`;
     db.all(query, (err: Error, row: any) => {
-      res(row.map((item: any) => parseToProduct(item)));
+      res(row?.map((item: any) => parseToProduct(item)) ?? []);
```
Comment (louis-jan) [inline electron/core/plugins/data-plugin/module.ts:171]: cc @namchuai

**Review by namchuai — APPROVED** [review]
