### PR TITLE
bug: support multiple line input chat using Textarea instead

### LINKED ISSUE #589: bug: I would like to input a paragraph (multiple lines)
**Describe the bug**
It seems like I can't use shift + enter to input a line break (\n)

### PR DESCRIPTION
**Pull request by urmauur**
Fix #589 

Solution:
Add new component textarea and make dynamic height based on scroll height of element

Result:

Screenshot 2023-11-11 at 17 25 15
Screenshot 2023-11-11 at 17 25 24

### CODE REVIEW

**Review by louis-jan — APPROVED** [review]

File: web/screens/Chat/index.tsx [hunk 1]
```diff
@@ -79,12 +82,24 @@ const ChatScreen = () => {
...
-      if (!event.shiftKey) {
-        event.preventDefault()
+  useEffect(() => {
+    if (textareaRef.current !== null) {
+      const scrollHeight = textareaRef.current.scrollHeight
+      if (currentPrompt.length === 0) {
+        textareaRef.current.style.height = '40px'
+      } else {
+        textareaRef.current.style.height = `${
+          scrollHeight < 40 ? 40 : scrollHeight
```
Comment (louis-jan) [inline web/screens/Chat/index.tsx:92]: cc @namchuai, input sizing back :D
