### PR TITLE
fix: #1183 Reveal in finder does not work on windows

### LINKED ISSUE #1183: bug: Reveal in Finder does not work in Windows, it has wrong slashes in the dir path
**Describe the bug**
Clicking on Reveal in Finder does not work, throws and error saying that it can't find, if you look at the path is trying to go, it has backwards slashes

**To Reproduce**
1. Go to 3 dots next to thread
2. Click on Reveal in inder
3. See error

**Expected behavior**
I would expect windows explorer would open to the right directory

**Screenshots**
image
Correct Path:
image

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 0.4.3

### PR DESCRIPTION
**Pull request by namchuai**
fixes #1183

### CODE REVIEW

File: web/screens/Chat/Sidebar/index.tsx [hunk 1]
```diff
@@ -54,23 +52,24 @@ const Sidebar: React.FC = () => {
...
       case 'Assistant':
         if (!assistantId) return
-        filePath = join('assistants', assistantId)
+        filePath = await janJoin(['assistants', assistantId])
         break
       default:
         break
     }
-
+    console.log('filepath', filePath)
```
Comment (namchuai) [inline web/screens/Chat/Sidebar/index.tsx:68]: self note: remove `console.log`

**Review by louis-jan — APPROVED** [review]
LGTM
