### PR TITLE
fix: #3549, #3552 - Inference on CPU is slower on Jan 0.5.3

### LINKED ISSUE #3549: bug: Inference on CPU is slower on Jan 0.5.3
**Problem**
I have Nvidia GPU in my PC, but when I want to run it with CPU with latest Jan (0.5.3), the speed is decrease significantly. Some machine with only CPU also met this problem.

**Explanation**
In 0.5.3, when your device has Nvidia GPU, we will delivery the non-AVX + Cuda acceleration version, since even when offload half of layers to GPU, the performance doesn't decrease too much. This update help us to serve more CPU architecture that doesn't support AVX2 instruction (default in prevs version). But when you run every thing in CPU, the performance will drop significantly

**Solution**
We have two cases to handle:
- With GPU acceleration:
     - we will bundle all: NoAVX + Cuda binary and AVX2 + Cuda binary  (this will require more storage on your device ~150Mb for each AVX option binary and ~400Mb for Cuda binary)
     - We go for a big epic - install engine in runtime, chose what version to install ( require more effort - time )
- CPU ONLY:
     -  Non-AVX + AVX + AVX2 + AVX512 for CPU only case (since they are small in terms of size)

### LINKED ISSUE #3552: bug: The model can't start / The specified module could not be found
### #

- [X] I have searched the existing issues

### Current behavior

The model can't start
In log "The specified module could not be found."
But i have
c:\Users\mik\AppData\Roaming\Jan\data\extensions\@janhq\inference-cortex-extension\dist\bin\win-cpu\engines\cortex.llamacpp\engine.dll

### Minimum reproduction step

1. Download JAN
2. Start
3. Select llama 3.1 instruct for download
4. wait
5. Start descusion

### Expected behavior

The conversation has begun.

### Screenshots / Logs

20240904 14:15:26.852000 UTC 19800 INFO  Server started, listening at: 127.0.0.1:3928 - main.cc:78
20240904 14:15:26.852000 UTC 19800 INFO  Please load your model - main.cc:79
20240904 14:15:26.852000 UTC 19800 INFO  Number of thread is:12 - main.cc:86
20240904 14:15:26.948000 UTC 23908 INFO  CPU instruction set: fpu = 1| mmx = 1| sse = 1| sse2 = 1| sse3 = 1| ssse3 = 1| sse4_1 = 1| sse4_2 = 1| pclmulqdq = 1| avx = 1| avx2 = 1| avx512_f = 1| avx512_dq = 1| avx512_ifma = 1| avx512_pf = 0| avx512_er = 0| avx512_cd = 1| avx512_bw = 1| has_avx512_vl = 1| has_avx512_vbmi = 1| has_avx512_vbmi2 = 1| avx512_vnni = 1| avx512_bitalg = 1| avx512_vpopcntdq = 1| avx512_4vnniw = 0| avx512_4fmaps = 0| avx512_vp2intersect = 0| aes = 1| f16c = 1| - server.cc:288
20240904 14:15:26.949000 UTC 23908 ERROR Could not load engine: Could not load library "C:\Users\mik\AppData\Roaming\Jan\data\extensions\@janhq\inference-cortex-extension\dist\bin\win-cpu/engines/cortex.llamacpp/engine.dll"
The specified module could not be found.

 - server.cc:299

2024-09-04T14:15:26.951Z [CORTEX]::Debug: Load model success with response {}
2024-09-04T14:15:26.951Z [CORTEX]::Debug: Validating model llama3.1-8b-instruct
2024-09-04T14:15:26.953Z [CORTEX]::Debug: Validate model state with response 409
2024-09-04T14:15:26.954Z [CORTEX]::Error: Validate model status failed
2024-09-04T14:15:26.954Z [CORTEX]::Debug: Validate model state failed with response {"message":"Engine is not loaded yet"} and status is "Conflict"

### Jan version

jan-win-x64-0.5.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

Win 11 x64

### PR DESCRIPTION
**Pull request by louis-jan**
## Problem
In version 0.5.3, the app ships with non-AVX binaries only (previously AVX2), which causes significant performance degradation, especially in CPU mode.

## Changes in this PR
**1. Fixed the app's inference performance degradation when running in CPU mode.  App bundles 7 binaries in total, including:**

Windows & Linux
- NO-AVX
- AVX
- AVX2
- AVX512
- VULKAN
- AVX2-CUDA-12-0
- AVX2-CUDA-11-7

MacOS
- ARM64
- X64

This would address the degradation issues with different CPU instructions where the app would pick the correct binary to run on optimized CPU instructions.

When GPU Acceleration settings is ON, the app will use AVX2-Cuda binaries by default (12.0 or 11.7, depending on the Cuda version installed by the user). This structure is the same as that of the llama.cpp releases and previous app releases.

**2. CPU acceleration when NGL is 0**

This fix added a small enhancement where the app will fall back to CPU mode when NGL is not defined or set to 0. (See #3549 discussions)
But it's quite confusing for now since on UX we only allow a minimum of 1

**3. Fixed the issue "The model can't start / The specified module could not be found"**

There is a fix included in the PR that allows the extension to locate the engine's DLLs file accordingly, so users will no longer encounter the issue above. 

Folder structure (the same for Linux but .so)
```bash
bin\
  cortex-cpp.exe
  [cortex-cpp].dll
  [engine-dependencies].dll
  win-avx\engines\engine.dll
  win-avx2\ngines\engine.dll
  win-cuda-12-0\ngines\engine.dll
  ...
```
There are no longer win-cpu and win-cuda. This is aligned with the releases structure.

**4. No more duplicate downloads of cortex-cpp binaries**
In previous releases, we shipped cortex-cpp under different folders, e.g., win-cpu/cortex-cpp and win-cuda/cortex-cpp. Now we introduce more binaries without duplicating them. Also, the structure is now aligned with llama.cpp releases.

For Windows and Linux (on Linux there is no .exe suffix, also .so instead of dll)

```bash
bin\
  cortex-cpp.exe
  [cortex-cpp].dll
  [engine-dependencies].dll
  win-noavx\engines\engine.dll  // Built with NOAVX flag
  win-avx\engines\engine.dll  // Built with AVX flag
  win-avx2\engines\engine.dll  // Built with AVX2 flag
  win-avx512\engines\engine.dll  // Built with AVX512 flag
  win-cuda-12-0\engines\engine.dll  // Built with AVX2, GGML_CUDA flag - CUDA 12.0 build env
  win-cuda-11-7\engines\engine.dll  // Built with AVX2, GGML_CUDA flag - CUDA 11.7 build env
  win-vulkan\engines\engine.dll  // Built with DGGML_VULKAN flag
  ...
```

For macOS, it will be a little bit different since cortex-cpp is built for a certain architecture. So it would be located under the platform-arch folder instead of bin.

```bash
bin\
  mac-arm64\
    cortex-cpp   // Build for ARM architecture
    engine.dylib
  mac-x64\
    cortex-cpp   // Build for X64 architecture
    engine.dylib
```

**5. Unit tests have been added to the extension.**
It's likely no tests were added to the extension, there are now 30 tests.

**6. Remove duplicated Cortex-CPP logics between the extension and API Server**
The model start use case from the current API server is quite confusing. The user should start the model from the API Server page before starting the API Server, so the /model/start case is not valid here since it is not synced to the UX. If it were, it should be implemented from cortex-cpp. I removed the duplicated and confusing logics from there in this PR.

| Performance increased significantly |
|:-:|
| CPU Only - with the fix > 14t/s - I9 13900K |
|Screenshot 2024-09-08 174450|
| CPU Only without the fix ~ 4t/s - I9 13900K |
|Screenshot 2024-09-08 174542|
| GPU Accelerated - The same ~120t/s - RTX 3090 |
| Screenshot 2024-09-08 174500|
| Offloaded - NGL 15 - The same ~23/s - RTX 3090 |
|Screenshot 2024-09-08 230608|
| Offloaded - NGL 1 - The same ~14/s - RTX 3090 |
|Screenshot 2024-09-08 230628
| Vulkan - The same ~54/s - RTX 3090 |
|Screenshot 2024-09-08 230914|
| MacOS - The same ~29/s - M2 Pro |
|Screenshot 2024-09-08 at 21 40 22|
| Linux - No AVX |
|Screenshot 2024-09-09 130650|
| Linux - AVX 2 |
|image|
## Fixes Issues

- Closes #3549
- Closes #3552

## To test this PR
Run: 
- Remove.jan extensions under Jan Data Folder (since a build for dev will not bump the version, no extensions migration is applied).
- `make clean`
- `make dev`
- Chat with a model

## What could be improved
How to deal with CUDA binaries on CPUs that do not support AVX2 instruction sets?
> Add NoAVX-CUDA and add 2 more heavy binaries
> Update UX to not allow GPU offload on unsupported instruction sets, or will it just crash without offload?

The same for the Vulkan binary, which is currently built with AVX2 by default for offloading?

## Self Checklist

- [x] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by hiento09 — APPROVED** [review]
lgtm

File: extensions/inference-nitro-extension/src/node/execute.ts [hunk 1]
```diff
@@ -1,37 +1,59 @@
...
+ * @param settings
+ * @returns
+ */
+const gpuRunMode = (settings?: GpuSetting): string => {
   if (process.platform === 'darwin')
     // MacOS now has universal binaries
     return ''
 
-  if (!settings) return 'cpu'
+  if (!settings) return ''
```
Comment (louis-jan) [inline extensions/inference-nitro-extension/src/node/execute.ts:21]: No more `-cpu` suffix, e.g. win-avx/win-avx512 (previously win-cpu). But cuda the same.

**Comment by dan-homebrew** [comment]
Review in progress

**Review by vansangpfiev — APPROVED** [review]

**Review by dan-homebrew — APPROVED** [review]
Great documentation of changes - I appreciate the effort put in on this.

**Comment by dan-homebrew** [comment]
I have linked this PR in https://github.com/janhq/cortex.cpp/discussions/1156, to document our use of llama.cpp

**Review by urmauur — APPROVED** [review]

**Comment by dan-homebrew** [comment]
@louis-jan Please merge and have @imtuyethan QA as part of 0.5.4 when you're ready

**Review by dan-homebrew — APPROVED** [review]
Lgtm!

**Comment by dan-homebrew** [comment]
@louis-jan Btw, let's standardize on `cortex.cpp`, instead of (Cortex-cpp)

**Comment by louis-jan** [comment]
> @louis-jan Btw, let's standardize on `cortex.cpp` or `cortexcpp` (if no period is allowed) instead of `Cortex-cpp`

Oops, that might break the executable from running, since the OS will now recognize it as a `.cpp` file instead of an `executable`.

**Comment by louis-jan** [comment]
Feature test build:

https://github.com/janhq/jan/actions/runs/10768992783

**Comment by Castafers** [comment]
> Feature test build:
> 
> https://github.com/janhq/jan/actions/runs/10768992783

I receive this error when testing the build, and trying Llama 3.1 8B like I always use.

`20240909 08:32:19.710231 UTC 18979 ERROR Unhandled exception in /inferences/server/loadmodel, what(): Value is not convertible to Int. - HttpAppFrameworkImpl.cc:124`

**Comment by Castafers** [comment]
> > https://github.com/janhq/jan/actions/runs/10768992783
> 
> Hi @Castafers, could you please take a screenshot of the download options you're seeing? I don't think the link is accessible without permission.

image

**Comment by louis-jan** [comment]
@Castafers Could you please help share your app.log? I will investigate further.

**Comment by Castafers** [comment]
> @Castafers Could you please help share your app.log? I will investigate further.

Sure thing, thank you for your contribution!
Here's the [logs](https://pastebin.com/TdxgJtLc).

**Comment by Castafers** [comment]
> > logs
> 
> Sorry the log file is not accessible.

I fixed it, my bad. Just trying to keep my information "unlisted" since I don't know what information are in those logs.

**Comment by louis-jan** [comment]
What a great find @Castafers, I have investigated and it turned out there is a regression in the latest dev build. We will fix it from there and update with a fixed build in this PR.

Regression found in this PR
https://github.com/janhq/jan/pull/3538

Reproduce: 
Adjust any context length or NGL reproduce a request with string values instead of numbers.

**Comment by Castafers** [comment]
> What a great find @Castafers, I have investigated and it turned out there is a regression in the latest dev build. We will fix it from there and update with a fixed build in this PR.
> 
> Regression found in this PR #3538
> 
> Reproduce: Adjust any context length or NGL reproduce a request with string values instead of numbers.

You're awesome :sunglasses: Thank you for the quick find and analysis from the logs!

**Comment by louis-jan** [comment]
Rebased `dev`

**Comment by louis-jan** [comment]
Hi @Castafers, here is the build with the latest fix, if you don't mind, please try this build and factory reset once again. Just to make sure there is no cache from a previous broken dev build. Thank you!
https://github.com/janhq/jan/actions/runs/10770763664

**Comment by Castafers** [comment]
> Hi @Castafers, here is the build with the latest fix from the `dev` branch, if you don't mind, please try this build and factory reset once again. Just to make sure there is no cache from a previous broken dev build. Thank you! https://github.com/janhq/jan/actions/runs/10770763664

The new build 625 is working nominally and performance is excellent.
Tokens dive from 102t/s to 68t/s, then begin fluctuating from 68t/s ~ 80t/s which I presume is normal now.

Thank you so much for fixing the severe performance bug! I hardly able to use the AI at all beforehand.
You are all awesome, from support to programmers to all contributors. This is a highly successful project & team :heart:
