### PR TITLE
feat(gguf): fix model compatibility heuristic for Apple Silicon unified memory

### LINKED ISSUE #6704: feat: improve model compatibility heuristic on Mac
## Problem Statement

The compatibility indicator for models on Mac currently relies on a rough heuristic (e.g., total RAM).

Example: gpt-oss-20b shows as `🟢 Recommended for your device` because the Mac has 16GB RAM. However, in practice, the model cannot run reliably due to resource limits (VRAM/CPU memory pressure

This leads to a misleading user experience, as the green indicator suggests models are fully supported when they may not run consistently.

## Feature Idea

Improve the compatibility heuristic for Mac

### PR DESCRIPTION
**Pull request by dataCenter430**
## Describe Your Changes

Add a dedicated `check_apple_silicon_compatibility()` helper with a two-component overhead model calibrated against real hardware:

| Component | Value | What it covers |
|---|---|---|
| Fixed | 2.5 GB | macOS kernel, WindowServer, Spotlight, Metal runtime init |
| Variable | 10% of total RAM | Metal GPU wired memory + driver state (scales with pool size) |

Resulting usable memory:

| Config | Usable | Old (wrong) |
|---|---|---|
| 8 GB M1 | ~4.7 GB | ~5.9 GB |
| 16 GB M2 | ~11.9 GB | ~13.9 GB |
| 32 GB M3 | ~26.3 GB | ~29.9 GB |
| 64 GB M3 Max | ~53.7 GB | ~61.9 GB |

Status thresholds for Apple Silicon:
- 🟢 **GREEN** — fits with ≥15% spare usable memory (comfortable, full Metal throughput)
- 🟡 **YELLOW** — fits but tight; memory pressure risk during long inference sessions
- 🔴 **RED** — exceeds usable memory; will page to disk or crash

The non-Mac code path (Windows, Linux, discrete GPU systems) is **unchanged**.

Left detailed doc comments in the commands.rs

## Fixes Issues

- Closes #6704 

## Testing

- [x] 8 GB Mac: 7B Q4_K_M (~4.1 GB) → 🟡 YELLOW (tight), 3B Q4_K_M (~1.7 GB) → 🟢 GREEN
- [x] 16 GB Mac: 20B Q4_K_M (~12 GB) → 🔴 RED, 13B Q4_K_M (~7.4 GB) → 🟢 GREEN
- [x] 32 GB Mac: 20B Q4_K_M (~12 GB) → 🟢 GREEN, 70B Q4_K_M (~40 GB) → 🔴 RED
- [x] Windows/Linux with discrete GPU: existing behavior unchanged

## Self Checklist

- [x] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

File: src-tauri/plugins/tauri-plugin-llamacpp/src/gguf/commands.rs [hunk 1]
```diff
@@ -86,19 +87,24 @@ pub async fn is_model_supported(
         kv_cache_size
     );
 
-    const RESERVE_BYTES: u64 = 2288490189;
+    // Apple Silicon: macOS with unified memory (no discrete GPUs detected).
+    // Requires a dedicated heuristic — see `check_apple_silicon_compatibility`.
+    if system_info.os_type == "macos" && system_info.gpus.is_empty() {
```
Comment (louis-jan) [inline src-tauri/plugins/tauri-plugin-llamacpp/src/gguf/commands.rs]: there is an arch information

**Comment by louis-jan** [comment]
@qnixsynapse what do you think about this?

File: src-tauri/plugins/tauri-plugin-llamacpp/src/gguf/commands.rs (hunk 1 above)
Comment (dataCenter430) [reply src-tauri/plugins/tauri-plugin-llamacpp/src/gguf/commands.rs]: Good catch! 👍 
I added `cpu.arch == "aarch64"` to the condition so Intel Macs with no discrete GPU (x86_64) don't accidentally take the Apple Silicon unified-memory path.
Thank you.
