### PR TITLE
fix: resolve MCP stdio transport disconnect and add auto-reconnect

### LINKED ISSUE #7787: bug: MCP server loses connection after 2-3 turns - "Transport closed" error
**Version:** 0.7.8

## Describe the Bug
The `sequential-thinking` MCP server consistently loses connection after 2-3 conversation turns, showing "Transport closed" errors. The server appears connected in the UI MCP Server config (green flag), but tool listing fails. Restarting the server temporarily fixes the issue, but it fails again after 2-3 more turns.

**Pattern:**
1. Server starts successfully ✅
2. Works for 2-3 conversation turns ✅
3. "Transport closed" errors appear ❌
4. Tool listing fails ❌
5. UI MCP Server config still shows "Connected" (misleading status) ❌
6. Restarting server fixes temporarily ✅
7. Cycle repeats (fails again after 2-3 turns) ❌

**Other MCP servers working:**
- `web_search_exa` (HTTP transport) - ✅ Works perfectly
- `fetch` (stdio transport) - ✅ Works perfectly  
- `sequential-thinking` (stdio transport) - ❌ Fails repeatedly

This appears to be a stdio transport issue specific to Windows. The same MCP server works fine when using HTTP transport manually.

## Steps to Reproduce
1. Enable `sequential-thinking` MCP server in Jan Settings → MCP Servers
2. Verify server shows "Connected" (green flag)
3. Start a conversation that uses the sequentialthinking tool
4. Have a conversation for 2-3 turns
5. Observe that tool calls stop working
6. Check Jan logs - see "Transport closed" errors

## Screenshots / Logs
```
[03:13:18] DEBUG Getting OpenClaw status
[03:13:18] DEBUG Getting OpenClaw status
[03:13:18] DEBUG starting new connection: https://mcp.exa.ai/
[03:13:18] WARN MCP server sequential-thinking failed to list tools: Transport closed
[03:13:18] WARN MCP server sequential-thinking failed to list tools: Transport closed
[03:13:20] DEBUG net.pipe://2f2f2e2f706970652f646f636b65725f656e67696e65/_ping
[03:13:20] INFO DockerSandbox: Docker ping failed: Error in the hyper legacy client: client error (Connect)
[03:13:20] DEBUG net.pipe://2f2f2e2f706970652f646f636b65725f656e67696e65/_ping
[03:13:20] INFO DockerSandbox: Docker ping failed: Error in the hyper legacy client: client error (Connect)
[03:13:20] INFO openclaw not installed yet, falling back to bun x
[03:13:20] INFO openclaw not installed yet, falling back to bun x
[03:42:20] DEBUG Getting OpenClaw status
[03:42:20] INFO Getting tunnel providers status
[03:42:20] INFO Getting status of all tunnel providers
[03:42:20] INFO Detecting Tailscale installation
[03:42:20] INFO Getting security status
[03:42:20] DEBUG Detecting ngrok installation
[03:42:20] DEBUG Detecting cloudflared installation
[03:42:22] DEBUG net.pipe://2f2f2e2f706970652f646f636b65725f656e67696e65/_ping
[03:42:22] INFO DockerSandbox: Docker ping failed: Error in the hyper legacy client: client error (Connect)
[03:42:22] INFO openclaw not installed yet, falling back to bun x
[03:42:54] DEBUG Getting OpenClaw status
[03:42:54] DEBUG starting new connection: https://mcp.exa.ai/
[03:42:54] WARN MCP server sequential-thinking failed to list tools: Transport closed
[03:42:55] WARN MCP server sequential-thinking failed to list tools: Transport closed
```
**MCP Configuration:**
```json
{
  "sequential-thinking": {
    "active": true,
    "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    "command": "npx",
    "env": {},
    "type": "stdio"
  },
  "mcpSettings": {
    "toolCallTimeoutSeconds": 60,
    "baseRestartDelayMs": 1000,
    "maxRestartDelayMs": 30000,
    "backoffMultiplier": 2,
    "proactiveMode": false
  }
}
```

## Operating System
- [ ] MacOS
- [x] Windows
- [ ] Linux

## Impact:
Severity: High - Breaks multi-turn tool-calling conversations
Frequency: 100% reproducible (fails every time after 2-3 turns)

### Suggested:

- Implement auto-reconnect when transport closes
- Add keep-alive messages to prevent timeout
- Fix pipe handle management
- Update UI status on MCP Server config to show accurate connection state

### Workaround: Manually restart MCP server every
2-3 turns (not sustainable)

### PR DESCRIPTION
**Pull request by dev-miro26**
### Problem
MCP servers using stdio transport (e.g., `sequential-thinking`) consistently lose connection after 2–3 conversation turns, showing "Transport closed" errors. The root causes are:
1. **Health monitoring was dead code** — `monitor_mcp_server_handle` was defined but never actually spawned, so no health checks ever ran
2. **No auto-reconnect** — when a stdio transport closed, the dead server entry remained in the HashMap indefinitely with no recovery mechanism
3. **Stale UI status** — `get_connected_servers` returned all entries in the HashMap including dead ones, so the UI showed a green "Connected" indicator even for servers whose transport had died
4. **Silent failures in `get_tools`** — "Transport closed" errors were caught and logged as warnings, but the dead server entry was never cleaned up, perpetuating the stale state
This made multi-turn tool-calling conversations unusable for stdio MCP servers, requiring manual restart every 2–3 turns.

### Fix
- Wire up `monitor_mcp_server_handle` which was defined but never called, so MCP servers now have active health monitoring (5-second check intervals)
- Implement auto-reconnect with exponential backoff when an MCP stdio transport closes, using the user-configured `McpSettings` (base delay, max delay, multiplier)
- Fix `get_tools` to remove dead servers from the HashMap when "Transport closed" errors are detected, and emit `mcp-update` events so the frontend reflects the actual connection state
- Fix misleading UI status by ensuring `get_connected_servers` no longer returns servers whose transport has died — dead entries are now cleaned up by both the monitor and `get_tools`
- Change `mcp_monitoring_tasks` type from `tokio::task::JoinHandle<()>` to `tauri::async_runtime::JoinHandle<()>` to match the return type of `tauri::async_runtime::spawn`

**Files changed:**
- `src-tauri/src/core/mcp/helpers.rs` — rewrote `monitor_mcp_server_handle` with reconnect logic; wired it up in `start_mcp_server`
- `src-tauri/src/core/mcp/commands.rs` — `get_tools` now removes dead servers and emits status events
- `src-tauri/src/core/state.rs` — fixed `JoinHandle` type mismatch

## Fixes Issues

- Closes #7787 

## Self Checklist

- [x] Added relevant comments, esp in complex areas
- [x] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by dev-miro26** [comment]
@louis-jan 
Could you please check this PR?
Leave your feedback kindly. 👍

**Comment by dev-miro26** [comment]
@louis-jan 
Could you please test and merge this PR?
I appreciate you. 👍

**Comment by dev-miro26** [comment]
Hi, @Vanalite
Could you please review this PR?

File: src-tauri/src/core/mcp/commands.rs [hunk 1]
```diff
@@ -162,36 +162,62 @@ pub async fn get_connected_servers(
...
-                continue;
+    {
+        let servers = state.mcp_servers.lock().await;
+        for (server_name, service) in servers.iter() {
+            let tools_future = service.list_all_tools();
+            let tools = match timeout(timeout_duration, tools_future).await {
+                Ok(Ok(tools)) => tools,
+                Ok(Err(e)) => {
+                    log::warn!("MCP server {} failed to list tools: {}", server_name, e);
+                    dead_servers.push(server_name.clone());
```
Comment (louis-jan) [inline src-tauri/src/core/mcp/commands.rs]: can it be removed from servers instead of adding dead_servers?

File: src-tauri/src/core/mcp/commands.rs [hunk 2]
```diff
@@ -161,37 +161,81 @@ pub async fn get_connected_servers(
...
+        servers.keys().cloned().collect()
+    };
+
+    for server_name in server_names {
+        let list_result = {
+            let servers = state.mcp_servers.lock().await;
+            let Some(service) = servers.get(&server_name) else {
+                continue;
+            };
+            timeout(timeout_duration, service.list_all_tools()).await
```
Comment (louis-jan) [inline src-tauri/src/core/mcp/commands.rs]:
```suggestion
            if let Some(service) = servers.get(&server_name) {
                timeout(timeout_duration, service.list_all_tools()).await
            };
```

**Comment by louis-jan** [comment]
@Vanalite Please feel free to merge after testing it today. fyi @dev-miro26 we are doing release cut so will proceed in 2hrs.

**Comment by dev-miro26** [comment]
@Vanalite 
Could you please test and merge this PR? 
I appreciate you.

**Comment by Vanalite** [comment]
```
You have access to a tool called "sequential-thinking" that you MUST use on EVERY turn.

Goal: solve this complex planning task step by step over many turns until I say "stop":

"I’m designing a full semester, 15‑week course on 'Introduction to AI Agents and Sandboxed Tooling' for senior CS students. The course should cover: LLM fundamentals, MCP architecture, sandbox runtimes (WASM, containers, micro‑VMs), security considerations, and a final project where students build a small agent that uses at least 3 different tools."

Rules:
1. On EVERY reply, first call the "sequential-thinking" tool with your current partial plan and questions.
2. After getting the tool result, refine the course design a bit more, then STOP and ask me: "Continue?".
3. Assume I will always answer "yes" for at least 10 turns.
4. Never skip the tool call, even if the plan looks finished. Keep iterating.

Let’s start now. First, call "sequential-thinking" to brainstorm the high‑level structure. Then wait for my "yes" before each next step.
```

@dev-miro26 I tested with this prompt using sequential-thinking tool via STDIO, after 2 rounds of triggering the tool, it still failed to reactivate the tool for later loop or later request. Can you verify again?

**Comment by dev-miro26** [comment]
@louis-jan  @Vanalite 
Could you please test again?
And hope to leave your some hints for this.
Thank you.

**Comment by Vanalite** [comment]
Look good now @dev-miro26.

**Comment by dev-miro26** [comment]
@louis-jan 
Vanalite approved this PR.
Could you please merge this PR?
Thank you.
