### PR TITLE
bug: enable delete conversation after deleted model

### LINKED ISSUE #588: bug: Not able to delete conversation after deleted model
**Describe the bug**
The trash bin button is hidden, only Download model button is displayed.

Screenshot 2023-11-11 at 12 09 04

### PR DESCRIPTION
**Pull request by urmauur**
Fix #588 

Result 
Screenshot 2023-11-11 at 21 02 54

### CODE REVIEW

File: web/screens/Chat/index.tsx [hunk 1]
```diff
@@ -101,31 +103,34 @@ const ChatScreen = () => {
...
-                        onClick={() => deleteConvo()}
-                      />
-                    )}
-                  </Fragment>
-                ) : (
-                  <div>
+                <div
+                  className={twMerge(
+                    'flex items-center space-x-3',
+                    downloadedModels.filter(
```
Comment (louis-jan) [inline web/screens/Chat/index.tsx:109]: check this in useState would reduce a rendering performance?

File: web/screens/Chat/index.tsx [hunk 2]
```diff
@@ -53,12 +55,22 @@ const ChatScreen = () => {
...
+  )
 
   useEffect(() => {
     getUserConversations()
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [])
 
+  useEffect(() => {
+    setIsModelAvailable(
+      downloadedModels.filter((x) => x.name === currentConvo?.name).length === 0
```
Comment (louis-jan) [inline web/screens/Chat/index.tsx:69]:
```suggestion
      downloadedModels.some((x) => x.name === currentConvo?.name)
```

**Review by louis-jan — APPROVED** [review]
